#pragma once

#include "spt\utils\portal_utils.hpp"

#ifdef SPT_PORTAL_UTILS

#define SPT_MONOCLE_FEATURE

#include "spt\feature.hpp"

#include "thirdparty\monocle_implicit_conversions.hpp"
#include "teleport_chain\generate.hpp"

#include <d3d9.h>
#include <wrl\client.h>

#include <thread>
#include <mutex>
#include <memory>

using Microsoft::WRL::ComPtr;

#define F_FMT "%.9g"
#define V_FMT F_FMT " " F_FMT " " F_FMT
#define V_UNP(v) (v).x, (v).y, (v).z

// same as vag trace feature
constexpr int SPT_PORTAL_SELECT_FLAGS = GPF_ALLOW_AUTO | GPF_ALLOW_OVERLAY | GPF_ONLY_OPEN_PORTALS;

struct d3d9_argb
{
	unsigned char b, g, r, a;

	explicit operator color32() const
	{
		return color32{.r = r, .g = g, .b = b, .a = a};
	}

	static d3d9_argb FromColor32(color32 c)
	{
		return d3d9_argb{.b = c.b, .g = c.g, .r = c.r, .a = c.a};
	}
};

#define MONOCLE_IMAGE_COLORS_X(X) \
	X(MIC_BORDER, d3d9_argb(200, 40, 200, 255)) \
	X(MIC_TP_EXCEEDED, d3d9_argb(0, 0, 0, 255)) \
	X(MIC_0CUM_BEHIND, d3d9_argb(0, 100, 100, 255)) \
	X(MIC_0CUM_FRONT, d3d9_argb(100, 100, 100, 255)) \
	X(MIC_1CUM_BEHIND, d3d9_argb(0, 255, 255, 255)) \
	X(MIC_1CUM_FRONT, d3d9_argb(255, 255, 255, 255)) \
	X(MIC_NEG1CUM, d3d9_argb(0, 0, 255, 255)) \
	X(MIC_2CUM, d3d9_argb(0, 255, 0, 255)) \
	X(MIC_NEG2CUM, d3d9_argb(0, 0, 150, 255)) \
	X(MIC_3CUM, d3d9_argb(0, 150, 0, 255)) \
	X(MIC_NEG3CUM, d3d9_argb(0, 0, 50, 255)) \
	X(MIC_MISC, d3d9_argb(255, 0, 0, 255)) \
	X(MIC_EFFECTIVE_TP_BORDER, d3d9_argb(255, 180, 0, 255))

enum MonocleImageColorType
{
#define X(name, _) name,
	MONOCLE_IMAGE_COLORS_X(X)
#undef X
	    MIC_COUNT,
};

inline const std::array<d3d9_argb, MIC_COUNT> DefaultMonocleImageColors{
#define X(_, color) color,
    MONOCLE_IMAGE_COLORS_X(X)
#undef X
};

inline std::array<d3d9_argb, MIC_COUNT> MonocleImageColors = DefaultMonocleImageColors;

struct WorkerMonocleData
{
	mon::PortalPair pp;
	mon::TeleportChainParams paramsTemplate; // paramsTemplate.pp points to pp

	WorkerMonocleData(const Vector& bluePos,
	                  const QAngle& blueAng,
	                  const Vector& orangePos,
	                  const QAngle& orangeAng,
	                  mon::PlacementOrder order,
	                  mon::GameVersion gv,
	                  const mon::TeleportChainParams& paramsTemplate)
	    : pp(bluePos, blueAng, orangePos, orangeAng, order, gv), paramsTemplate(paramsTemplate)
	{
		this->paramsTemplate.pp = &pp;
	}
};

struct WorkerPixel
{
	uint16_t x, y;

	bool operator==(WorkerPixel o) const
	{
		return x == o.x && y == o.y;
	}
};

struct WorkerPixelData
{
	uint8_t tpExceeded : 1;
	uint8_t endBehindPortal : 1;
	int8_t cumTp : 6;

	constexpr MonocleImageColorType ToColor() const
	{
		if (tpExceeded)
			return MIC_TP_EXCEEDED;
		switch (cumTp)
		{
		case 0:
			return endBehindPortal ? MIC_0CUM_BEHIND : MIC_0CUM_FRONT;
		case 1:
			return endBehindPortal ? MIC_1CUM_BEHIND : MIC_1CUM_FRONT;
		case -1:
			return MIC_NEG1CUM;
		case 2:
			return MIC_2CUM;
		case -2:
			return MIC_NEG2CUM;
		case 3:
			return MIC_3CUM;
		case -3:
			return MIC_NEG3CUM;
		default:
			return MIC_MISC;
		}
	}
};

/*
* Runs monocle for each pixel on a separate thread. The worker thread writes the monocle result to
* an "image", and the render (main) thread periodically uploads rows of that image to a dx9
* texture. State diagram:
* 
* +-------------+  +-------+  +----+
* |Uninitialized|->|Working|->|Idle|
* +-------------+  +-------+  +----+
*                   ^     |    |
*                   |     v    v
*                   +--RestartWork()
* 
* You can grab information about the job only once RestartWork() has been called at least once.
*/
class MonocleWorker
{
public:
private:
	std::shared_ptr<const WorkerMonocleData> monocleData;
	std::thread thread;
	std::mutex mtx;
	std::condition_variable cvWorker;
	std::condition_variable cvMain;
	bool requestPause = true;
	bool requestStop = false;
	bool paused = false;

	// the monocle result generated by the worker thread
	struct
	{
		std::unique_ptr<WorkerPixelData[]> pxls;
		WorkerPixel size;
		std::atomic<uint16_t> processedRows = 0;

		/*
		* A quad in pixel space that represents a set outside of which it is normally not possible
		* to enter this portal (e.g. the pixel is very close to the portal edge). This data is not
		* needed by the worker but it's the best place to put it.
		*/
		std::array<Vector2D, 4> effectiveTpSpace;
	} img;

	// the actual texture displayed in imgui
	struct
	{
		ComPtr<IDirect3DTexture9> texture = nullptr;
		uint16_t nRowsUploaded = 0;
	} tex;

public:
	MonocleWorker();
	~MonocleWorker();

	auto& GetMonocleData()
	{
		return monocleData;
	}

	auto& GetMonocleData() const
	{
		return monocleData;
	}

	auto& GetEffectiveTpSpace() const
	{
		return img.effectiveTpSpace;
	}

	void RestartWork(std::shared_ptr<WorkerMonocleData> optNewMonocleData, WorkerPixel newImgSize);

	void MarkTextureDirty()
	{
		tex.nRowsUploaded = 0;
	}

	ComPtr<IDirect3DTexture9> UpdateAndGetTexture();

	WorkerPixel GetImageSize() const
	{
		return img.size;
	}

	Vector PixelToWorldCoordinates(WorkerPixel px, const mon::TeleportChainParams* paramsOverride = nullptr) const;

	std::optional<WorkerPixelData> GetPixelResult(WorkerPixel px) const
	{
		if (!img.pxls || img.processedRows < px.y || !monocleData)
			return {};
		return img.pxls[px.y * img.size.x + px.x];
	}

	WorkerPixelData DoWorkForPixel(WorkerPixel px,
	                               const mon::TeleportChainParams& paramsTemplate,
	                               mon::TeleportChainResult& result) const;

	static std::optional<bool> EndBehindPortal(const mon::TeleportChainParams& params,
	                                           const mon::TeleportChainResult& result);

private:
	void SetupTexture();
	void PauseWorker();
	void WorkerLoop();
	void RecomputeEffectiveTpSpace();
};

class MonocleFeature : public FeatureWrapper<MonocleFeature>
{
private:
	std::shared_ptr<MonocleWorker> worker1, worker2;

	struct Tooltip
	{
		int pxlWidth = 20;
		float zoom = 10.f;
	} tooltip;

	struct
	{
		bool enabled = true;
		float thickness = 2.f;
		float tooltipThickness = 2.f;
	} effectiveTpSpace;

	void DrawWorkerImage(const char* label, MonocleWorker& wd);

	struct UserPixelSelect
	{
		WorkerPixel selectedPxl{};
		WorkerPixel imgSize{};
		mon::TeleportChainParams params; // params.pp may not be valid
		mon::TeleportChainResult result;
		bool bluePlacedLast = false;
		bool dirty = true;

		void Update(const MonocleWorker& wd, WorkerPixel pxl, bool bluePlacedLast_);
		void DrawInfo();
	};

	UserPixelSelect hoveredPxl;

	void OnTickSignal(bool);

	void ImGuiTabCallback();
	bool ImGuiDrawSettings(); // returns true when settings change
	bool CheckPortalsChanged(const utils::PortalInfo* newEntryPortal);
	void RestartWorkers(const utils::PortalInfo* newEntryPortal);
	void ImGuiDrawImages();
	void ImGuiColorEditSettings();

protected:
	virtual bool ShouldLoadFeature() override;
	virtual void LoadFeature() override;
	virtual void UnloadFeature() override;
} inline spt_monocle_feat;

#endif
